spring:
  profiles:
    active:
    - dev

---
server:
  port: 8201
spring:
  profiles: dev   #开发环境
  application:
    name: microservicecloud-config-client
eureka:
  client:
    server-url:
      defaultZone: http://eureke-dev.com:7001/eureka/
---
server:
  port: 8202
spring:
  profiles: test   #开发环境
  application:
    name: microservicecloud-config-client
eureka:
  client:
    server-url:
      defaultZone: http://eureke-dev.com:7001/eureka/